experiment:
  group_name: "ANN_turtle"
  save_dir: "models/"

data:
  train_path: "data/training_set.h5"
  val_path: "data/validation_set.h5"
  batch_size: 1000
  target_col: "Z" 
  inputs:
    FilterJPAS: [
      'J0378', 'J0390', 'J0400', 'J0410', 'J0420', 'J0430', 'J0440', 'J0450',
      'J0460', 'J0470', 'J0480', 'J0490', 'J0500', 'J0510', 'J0520', 'J0530',
      'J0540', 'J0550', 'J0560', 'J0570', 'J0580', 'J0590', 'J0600', 'J0610',
      'J0620', 'J0630', 'J0640', 'J0650', 'J0660', 'J0670', 'J0680', 'J0690',
      'J0700', 'J0710', 'J0720', 'J0730', 'J0740', 'J0750', 'J0760', 'J0770',
      'J0780', 'J0790', 'J0800', 'J0810', 'J0820', 'J0830', 'J0840', 'J0850',
      'J0860', 'J0870', 'J0880', 'J0890', 'J0900', 'J0910'
    ]
    MAGNITUDES: [
      'MAG_NUV','MAG_FUV','MAG_G','MAG_R','MAG_i','MAG_Z',"MAG_J_2MASS",
      "MAG_H_2MASS","MAG_Ks_2MASS",'MAG_W1','MAG_W2','MAG_W3','MAG_W4', 'iSDSS'
    ]

  selected_features: ["FilterJPAS", "MAGNITUDES"] 
  
  features_to_normalize: ["MAGNITUDES"] 

model:
  type: "neural_net" # Options: "neural_net", "random_forest"
  
  # Neural network parameters
  hidden_layers: [512,512,512]
  dropout_rates: [0.3, 0.3] 
  output_size: 1
  
  # Random Forest parameters
  n_estimators: 500
  max_depth: 100

training:
  epochs: 100
  learning_rate: 0.001
  loss_type: "deltaz"
